version: '3.9'

services:
  app:
    container_name: fanclub_api
    build:
      context: src
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src
    depends_on:
      - db
      - cache
    env_file:
      - src/.env
    networks:
      - fanclub

  nginx:
    container_name: fanclub_proxy
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - fanclub

  db:
    container_name: fanclub_db
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - fanclub

  cache:
    container_name: fanclub_cache
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - fanclub

networks:
  fanclub:

volumes:
  db-data:
  cache:
