// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// Billboard is the predicate function for billboard builders.
type Billboard func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)
