// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hackgame-org/fanclub_api/ent/asset"
	"github.com/hackgame-org/fanclub_api/ent/billboard"
	"github.com/hackgame-org/fanclub_api/ent/post"
	"github.com/hackgame-org/fanclub_api/ent/predicate"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (au *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetPublicID sets the "public_id" field.
func (au *AssetUpdate) SetPublicID(s string) *AssetUpdate {
	au.mutation.SetPublicID(s)
	return au
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (au *AssetUpdate) SetNillablePublicID(s *string) *AssetUpdate {
	if s != nil {
		au.SetPublicID(*s)
	}
	return au
}

// SetURL sets the "url" field.
func (au *AssetUpdate) SetURL(s string) *AssetUpdate {
	au.mutation.SetURL(s)
	return au
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (au *AssetUpdate) SetNillableURL(s *string) *AssetUpdate {
	if s != nil {
		au.SetURL(*s)
	}
	return au
}

// SetResourceType sets the "resource_type" field.
func (au *AssetUpdate) SetResourceType(s string) *AssetUpdate {
	au.mutation.SetResourceType(s)
	return au
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (au *AssetUpdate) SetNillableResourceType(s *string) *AssetUpdate {
	if s != nil {
		au.SetResourceType(*s)
	}
	return au
}

// SetCreatedAt sets the "created_at" field.
func (au *AssetUpdate) SetCreatedAt(t time.Time) *AssetUpdate {
	au.mutation.SetCreatedAt(t)
	return au
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (au *AssetUpdate) SetNillableCreatedAt(t *time.Time) *AssetUpdate {
	if t != nil {
		au.SetCreatedAt(*t)
	}
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AssetUpdate) SetUpdatedAt(t time.Time) *AssetUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetBillboardID sets the "billboard" edge to the Billboard entity by ID.
func (au *AssetUpdate) SetBillboardID(id uuid.UUID) *AssetUpdate {
	au.mutation.SetBillboardID(id)
	return au
}

// SetNillableBillboardID sets the "billboard" edge to the Billboard entity by ID if the given value is not nil.
func (au *AssetUpdate) SetNillableBillboardID(id *uuid.UUID) *AssetUpdate {
	if id != nil {
		au = au.SetBillboardID(*id)
	}
	return au
}

// SetBillboard sets the "billboard" edge to the Billboard entity.
func (au *AssetUpdate) SetBillboard(b *Billboard) *AssetUpdate {
	return au.SetBillboardID(b.ID)
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (au *AssetUpdate) SetPostID(id uuid.UUID) *AssetUpdate {
	au.mutation.SetPostID(id)
	return au
}

// SetNillablePostID sets the "post" edge to the Post entity by ID if the given value is not nil.
func (au *AssetUpdate) SetNillablePostID(id *uuid.UUID) *AssetUpdate {
	if id != nil {
		au = au.SetPostID(*id)
	}
	return au
}

// SetPost sets the "post" edge to the Post entity.
func (au *AssetUpdate) SetPost(p *Post) *AssetUpdate {
	return au.SetPostID(p.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (au *AssetUpdate) Mutation() *AssetMutation {
	return au.mutation
}

// ClearBillboard clears the "billboard" edge to the Billboard entity.
func (au *AssetUpdate) ClearBillboard() *AssetUpdate {
	au.mutation.ClearBillboard()
	return au
}

// ClearPost clears the "post" edge to the Post entity.
func (au *AssetUpdate) ClearPost() *AssetUpdate {
	au.mutation.ClearPost()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AssetUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AssetUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AssetUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AssetUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

func (au *AssetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.PublicID(); ok {
		_spec.SetField(asset.FieldPublicID, field.TypeString, value)
	}
	if value, ok := au.mutation.URL(); ok {
		_spec.SetField(asset.FieldURL, field.TypeString, value)
	}
	if value, ok := au.mutation.ResourceType(); ok {
		_spec.SetField(asset.FieldResourceType, field.TypeString, value)
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if au.mutation.BillboardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   asset.BillboardTable,
			Columns: []string{asset.BillboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billboard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.BillboardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   asset.BillboardTable,
			Columns: []string{asset.BillboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billboard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.PostTable,
			Columns: []string{asset.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.PostTable,
			Columns: []string{asset.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetPublicID sets the "public_id" field.
func (auo *AssetUpdateOne) SetPublicID(s string) *AssetUpdateOne {
	auo.mutation.SetPublicID(s)
	return auo
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (auo *AssetUpdateOne) SetNillablePublicID(s *string) *AssetUpdateOne {
	if s != nil {
		auo.SetPublicID(*s)
	}
	return auo
}

// SetURL sets the "url" field.
func (auo *AssetUpdateOne) SetURL(s string) *AssetUpdateOne {
	auo.mutation.SetURL(s)
	return auo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (auo *AssetUpdateOne) SetNillableURL(s *string) *AssetUpdateOne {
	if s != nil {
		auo.SetURL(*s)
	}
	return auo
}

// SetResourceType sets the "resource_type" field.
func (auo *AssetUpdateOne) SetResourceType(s string) *AssetUpdateOne {
	auo.mutation.SetResourceType(s)
	return auo
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (auo *AssetUpdateOne) SetNillableResourceType(s *string) *AssetUpdateOne {
	if s != nil {
		auo.SetResourceType(*s)
	}
	return auo
}

// SetCreatedAt sets the "created_at" field.
func (auo *AssetUpdateOne) SetCreatedAt(t time.Time) *AssetUpdateOne {
	auo.mutation.SetCreatedAt(t)
	return auo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auo *AssetUpdateOne) SetNillableCreatedAt(t *time.Time) *AssetUpdateOne {
	if t != nil {
		auo.SetCreatedAt(*t)
	}
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AssetUpdateOne) SetUpdatedAt(t time.Time) *AssetUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetBillboardID sets the "billboard" edge to the Billboard entity by ID.
func (auo *AssetUpdateOne) SetBillboardID(id uuid.UUID) *AssetUpdateOne {
	auo.mutation.SetBillboardID(id)
	return auo
}

// SetNillableBillboardID sets the "billboard" edge to the Billboard entity by ID if the given value is not nil.
func (auo *AssetUpdateOne) SetNillableBillboardID(id *uuid.UUID) *AssetUpdateOne {
	if id != nil {
		auo = auo.SetBillboardID(*id)
	}
	return auo
}

// SetBillboard sets the "billboard" edge to the Billboard entity.
func (auo *AssetUpdateOne) SetBillboard(b *Billboard) *AssetUpdateOne {
	return auo.SetBillboardID(b.ID)
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (auo *AssetUpdateOne) SetPostID(id uuid.UUID) *AssetUpdateOne {
	auo.mutation.SetPostID(id)
	return auo
}

// SetNillablePostID sets the "post" edge to the Post entity by ID if the given value is not nil.
func (auo *AssetUpdateOne) SetNillablePostID(id *uuid.UUID) *AssetUpdateOne {
	if id != nil {
		auo = auo.SetPostID(*id)
	}
	return auo
}

// SetPost sets the "post" edge to the Post entity.
func (auo *AssetUpdateOne) SetPost(p *Post) *AssetUpdateOne {
	return auo.SetPostID(p.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (auo *AssetUpdateOne) Mutation() *AssetMutation {
	return auo.mutation
}

// ClearBillboard clears the "billboard" edge to the Billboard entity.
func (auo *AssetUpdateOne) ClearBillboard() *AssetUpdateOne {
	auo.mutation.ClearBillboard()
	return auo
}

// ClearPost clears the "post" edge to the Post entity.
func (auo *AssetUpdateOne) ClearPost() *AssetUpdateOne {
	auo.mutation.ClearPost()
	return auo
}

// Where appends a list predicates to the AssetUpdate builder.
func (auo *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Asset entity.
func (auo *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AssetUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

func (auo *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.PublicID(); ok {
		_spec.SetField(asset.FieldPublicID, field.TypeString, value)
	}
	if value, ok := auo.mutation.URL(); ok {
		_spec.SetField(asset.FieldURL, field.TypeString, value)
	}
	if value, ok := auo.mutation.ResourceType(); ok {
		_spec.SetField(asset.FieldResourceType, field.TypeString, value)
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if auo.mutation.BillboardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   asset.BillboardTable,
			Columns: []string{asset.BillboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billboard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.BillboardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   asset.BillboardTable,
			Columns: []string{asset.BillboardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billboard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.PostTable,
			Columns: []string{asset.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.PostTable,
			Columns: []string{asset.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Asset{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
