// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hackgame-org/fanclub_api/ent/asset"
	"github.com/hackgame-org/fanclub_api/ent/billboard"
)

// BillboardCreate is the builder for creating a Billboard entity.
type BillboardCreate struct {
	config
	mutation *BillboardMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (bc *BillboardCreate) SetTitle(s string) *BillboardCreate {
	bc.mutation.SetTitle(s)
	return bc
}

// SetDescription sets the "description" field.
func (bc *BillboardCreate) SetDescription(s string) *BillboardCreate {
	bc.mutation.SetDescription(s)
	return bc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (bc *BillboardCreate) SetNillableDescription(s *string) *BillboardCreate {
	if s != nil {
		bc.SetDescription(*s)
	}
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BillboardCreate) SetCreatedAt(t time.Time) *BillboardCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BillboardCreate) SetNillableCreatedAt(t *time.Time) *BillboardCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BillboardCreate) SetUpdatedAt(t time.Time) *BillboardCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BillboardCreate) SetNillableUpdatedAt(t *time.Time) *BillboardCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BillboardCreate) SetID(u uuid.UUID) *BillboardCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bc *BillboardCreate) SetNillableID(u *uuid.UUID) *BillboardCreate {
	if u != nil {
		bc.SetID(*u)
	}
	return bc
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (bc *BillboardCreate) SetAssetID(id uuid.UUID) *BillboardCreate {
	bc.mutation.SetAssetID(id)
	return bc
}

// SetNillableAssetID sets the "asset" edge to the Asset entity by ID if the given value is not nil.
func (bc *BillboardCreate) SetNillableAssetID(id *uuid.UUID) *BillboardCreate {
	if id != nil {
		bc = bc.SetAssetID(*id)
	}
	return bc
}

// SetAsset sets the "asset" edge to the Asset entity.
func (bc *BillboardCreate) SetAsset(a *Asset) *BillboardCreate {
	return bc.SetAssetID(a.ID)
}

// Mutation returns the BillboardMutation object of the builder.
func (bc *BillboardCreate) Mutation() *BillboardMutation {
	return bc.mutation
}

// Save creates the Billboard in the database.
func (bc *BillboardCreate) Save(ctx context.Context) (*Billboard, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BillboardCreate) SaveX(ctx context.Context) *Billboard {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BillboardCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BillboardCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BillboardCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := billboard.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := billboard.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.ID(); !ok {
		v := billboard.DefaultID()
		bc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BillboardCreate) check() error {
	if _, ok := bc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Billboard.title"`)}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Billboard.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Billboard.updated_at"`)}
	}
	return nil
}

func (bc *BillboardCreate) sqlSave(ctx context.Context) (*Billboard, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BillboardCreate) createSpec() (*Billboard, *sqlgraph.CreateSpec) {
	var (
		_node = &Billboard{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(billboard.Table, sqlgraph.NewFieldSpec(billboard.FieldID, field.TypeUUID))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bc.mutation.Title(); ok {
		_spec.SetField(billboard.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bc.mutation.Description(); ok {
		_spec.SetField(billboard.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(billboard.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(billboard.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := bc.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   billboard.AssetTable,
			Columns: []string{billboard.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BillboardCreateBulk is the builder for creating many Billboard entities in bulk.
type BillboardCreateBulk struct {
	config
	err      error
	builders []*BillboardCreate
}

// Save creates the Billboard entities in the database.
func (bcb *BillboardCreateBulk) Save(ctx context.Context) ([]*Billboard, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Billboard, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillboardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BillboardCreateBulk) SaveX(ctx context.Context) []*Billboard {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BillboardCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BillboardCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
