name: Test, Build and Deploy Go Application

# Defines events to trigger the GitHub Actions
# Push and pull request to main branch trigger this workflows
on:
  push:
    branches: main
  pull_request: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    # Set the default working directory to /src
    defaults:
      run:
        working-directory: ./src
    # Set the multiple versions
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21.x"]

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Golang
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      # Build test
      - name: Build
        run: go build

      # Run unit tests
      - name: Test
        run: cd tests
          go test  -v ./...
